rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3

before_install:
  - "gem install bundler -v=1.3.0"
before_script:
  - "bundle install"

script: "bundle exec rake test"

gemfile:
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile

matrix:
  exclude:
    - rvm: ree
      gemfile: gemfiles/4.0.gemfile
